### ISSUE TITLE
Pump

### ISSUE THREAD

**Issue by DietmarWeisse** [petergridge/Irrigation-V5#59] opened 2024-03-21 15:53 UTC
If I turn on the pump without a program, it switches off again after a few seconds,

**Comment by petergridge** [comment] 2024-03-21 20:50
Hi Dietmar,

The control monitors the zones and disables the pump if no zone is active. 

I will look at the process, I will look to change the monitoring to only when a program is activated.

regards
Pete

**Comment by petergridge** [comment] 2024-03-21 21:14
Hi,

This should be behaving, can you check the logs, are you getting any errors?

Cheers
Pete

**Comment by DietmarWeisse** [comment] 2024-03-22 08:11
Hello, I installed 5.4.9 again and now the error has not occurred anymoreDietmar Sent from my iPhoneOn 21 Mar 2024, at 22:14, Peter ***@***.***> wrote:﻿
Hi,
This should be behaving, can you check the logs, are you getting any errors?
Cheers
Pete

**Comment by schimi42** [comment] 2024-04-02 18:22
Hi Pete,
I'm having the exact same issue. For now I removed the pump switch from the configuration and I can control it manually again. Do you have an idea when you can release the fix? My workaround would be to trigger an additional automation to switch on the pump when the program starts and switch it off when it's done. But if you plan to release the fix anytime soon I'm going to wait. :)
Thanks
Schimi42

**Comment by petergridge** [comment] 2024-04-03 02:40
I am just testing the changes now, I will release a Beta tomorrow, please let me know if you experience any issues once you install.

**Comment by petergridge** [comment] 2024-04-03 03:02
V5.4.10 released as Beta.

**Comment by schimi42** [comment] 2024-04-03 19:11
I installed the beta today and the issue is gone. I will do some additional tests tomorrow to see if everything works as expected. Thanks for the quick response!

**Comment by schimi42** [comment] 2024-04-13 18:09
Not sure what happened but the issue with the pump switching off when manually activated outside of the irrigation system is/was back. I removed the pump from the irrigation configuration, restarted home assistant and then I was able to control the pump again. Then I added the pump back to the configuration, let the program run once and now it works again. Will keep monitoring the behavior. But there might be an additional issue.

**Comment by DietmarWeisse** [comment] 2024-04-14 10:47
HELLO, I also have the same errorThank youDietmar Von meinem iPhone gesendetAm 13.04.2024 um 20:10 schrieb schimi42 ***@***.***>:﻿
Not sure what happened but the issue with the pump switching off when manually activated outside of the irrigation system is/was back. I removed the pump from the irrigation configuration, restarted home assistant and then I was able to control the pump again. Then I added the pump back to the configuration, let the program run once and now it works again. Will keep monitoring the behavior. But there might be an additional issue.

**Comment by petergridge** [comment] 2024-04-15 02:35
Hi, 

Can you send me the details of your configuration.

The control starts a monitoring service when a program of zone is started. Once the program or zone ends the service should also be shut off. 

The things to look for are overlapping program starts, manual starts of a zone or program. It would be great to get the sequence of events that causes this issue to show itself.

I will run some tests to see if I can duplicate the problem.

Cheers
Pete

**Comment by schimi42** [comment] 2024-04-15 07:56
Hi, is there a way to export the configuration?

**Comment by petergridge** [comment] 2024-04-15 08:30
No,  it's on my to-do list,  I have been wanting  to write a function to output the config as yaml to the log file. It's not complex, but finding the time. In mid renovation at the moment fitting this in between grinding floors and painting👷‍♂️

**Comment by petergridge** [comment] 2024-04-15 08:33
I did find that it takes a few seconds to stop the monitoring, that was the only scenario I could make it happen, turn off a zone and then immediately turn on the pump. 

I have a fix but I will wait to see what you find before I release it.

**Comment by schimi42** [comment] 2024-04-15 18:41
It's not related to the timing you described. Even hours after the program ran it still switches off the pump. 
I don't have a very complex configuration. 2 programs, the first one with two zones, the other with one zone. A rain sensor is configured for all zones. 

What I do not have configured is a delay between the two zones. Maybe that's the issue? How long does the monitoring service run after the zone is completed? I would like to try adding a suitable delay to test it.

**Comment by schimi42** [comment] 2024-04-16 09:55
I added a delay of 10 seconds yesterday evening. After a restart of HA I was able to control the pump manually. This morning the program did not run due the rain sensor being activated. However, now I cannot control the pump manually, it switches off after a few seconds. 

Not sure if it helps - this is the extract from the core.config_entries file for one of the programs:

`      {
        "entry_id": "eff050b6e92e04f3f93b96436575d753",
        "version": 4,
        "minor_version": 1,
        "domain": "irrigationprogram",
        "title": "Bewässerung Rasen",
        "data": {
          "name": "Bewässerung Rasen",
          "start_time": "input_datetime.bewasserung_rasen_startzeit",
          "device_type": "generic",
          "interlock": true,
          "run_freq": "input_select.bewasserung_rasen_haufigkeit",
          "irrigation_on": "input_boolean.bewasserung_rasen_an_aus",
          "zones": [
            {
              "zone": "switch.rasen_vorgarten",
              "water": "input_number.bewasserung_rasen_dauer",
              "pump": "switch.gartenpumpe",
              "rain_sensor": "input_boolean.bewasserung_regensensor"
            },
            {
              "zone": "switch.sprinkler_rasen_garten",
              "water": "input_number.bewasserung_rasen_dauer",
              "pump": "switch.gartenpumpe",
              "rain_sensor": "input_boolean.bewasserung_regensensor"
            }
          ]
        },
        "options": {
          "name": "Bewässerung Rasen",
          "start_time": "input_datetime.bewasserung_rasen_startzeit",
          "device_type": "generic",
          "zones": [
            {
              "zone": "switch.rasen_vorgarten",
              "water": "input_number.bewasserung_rasen_dauer",
              "pump": "switch.gartenpumpe",
              "rain_sensor": "input_boolean.bewasserung_rasen_regensensor",
              "wait": "input_number.bewassung_pause_zwischen_zonen"
            },
            {
              "zone": "switch.sprinkler_rasen_garten",
              "water": "input_number.bewasserung_rasen_dauer",
              "pump": "switch.gartenpumpe",
              "rain_sensor": "input_boolean.bewasserung_rasen_regensensor",
              "wait": "input_number.bewassung_pause_zwischen_zonen"
            }
          ],
          "xx": "y",
          "run_freq": "input_select.bewasserung_rasen_haufigkeit",
          "irrigation_on": "input_boolean.bewasserung_rasen_an_aus",
          "interlock": true,
          "inter_zone_delay": "input_number.bewassung_pause_zwischen_zonen"
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      },
`

**Comment by petergridge** [comment] 2024-04-17 09:03
I've tried everything I can think of.
1. program with overlapping start times with Program2 terminating Program1
2. stopping the program prematurely
3. stopping a zone while the program is running
4. manual start of a zone
5. manual start of a program 
6. manual start of a zone and stopping prematurely
7. manual start of a program and stopping prematurely

What hardware are you running on?

**Comment by schimi42** [comment] 2024-04-17 19:12
I'm using HA OS on an Intel NUC. Native, no virtualization. 
I'll set up another HA instance for testing. Maybe I can replicate the issue.

**Comment by schimi42** [comment] 2024-04-19 08:42
Also with a fresh installation I get the same error. Tried different configuration variants (1 zone, 2 zones, with and without  rain sensor, etc.) but the issue remains. The pump switches off after a few seconds when activated manually. 
I activated the debug logging but there are no messages from the integration.

**Comment by petergridge** [comment] 2024-04-19 10:13
I will put a release up with some additional warning messages around the pump monitoring process. It will be a couple of days before I will get to it though

**Comment by schimi42** [comment] 2024-04-19 13:11
Shame on me - on the new installation I had the 5.4.9 version installed. Now upgraded to 5.4.10 and the issue is gone. Will monitor the test installation to see if that changes. 
But on my life system I already have the 5.4.10 and the issue remains.

**Comment by petergridge** [comment] 2024-04-21 10:35
Hi @schimi42, I have added some warning messages into Version 5.4.11 to write what is happening in the monitoring.

you should see these in the log
![image](https://github.com/petergridge/Irrigation-V5/assets/40281772/71469083-d519-4237-9886-44abde078986)

Each program you run that uses a pump should start monitoring as the program starts and stop monitoring as the program ends.

Let me know what result you get, I will need to remove these messages before publishing a new version.

Cheers
Pete

**Comment by schimi42** [comment] 2024-04-21 13:03
Hi Pete,
I installed the new version and added the pump back to the configuration. I also see the warnings in the log file. Now I need to wait for the issue to reoccur. 
Thanks for your support with this issue!

**Comment by schimi42** [comment] 2024-04-22 09:05
Hi Pete, here's what I found with the new log messages.

My first irrigation program is supposed to start at 4:30. But because the rain sensor was active the program was not started. This is what I see in the log file:

2024-04-22 04:30:00.003 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class Started monitoring zones ['switch.rasen_vorgarten', 'switch.sprinkler_rasen_garten']

At 7:01 I tried to activate the pump manually and it switched off again. This is the log entry:

2024-04-22 07:01:55.303 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump

The second program starts at 8:00 and for this zone the rain sensor was not active. What happened then was the the pump was switched on and off every few seconds probably because both monitors were acting against each other:

2024-04-22 08:00:00.007 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class Started monitoring zones ['switch.bewasserung_sprinkler_beete']
2024-04-22 08:00:07.787 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump
2024-04-22 08:00:23.815 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump
2024-04-22 08:00:39.833 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump
2024-04-22 08:00:55.854 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump
2024-04-22 08:01:04.146 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitoring has stopped

Another try at 10:50 to turn on the pump manually resulted in the same behavior:
2024-04-22 10:50:36.829 WARNING (MainThread) [custom_components.irrigationprogram.pump] Pump Class zone monitor has turned off pump

Does that help?

**Comment by petergridge** [comment] 2024-04-22 09:41
That's great, this has been a hard one to track down thanks. I'll try to get a fix out soon

**Comment by petergridge** [comment] 2024-04-24 04:45
V5.4.13 has been released,
A few fixes, your issue should be resolved now, and I have added a service to write the config to the log file

**Comment by schimi42** [comment] 2024-04-28 04:20
Hi Pete,

I have upgraded to the new release and so far it's working fine. Will keep monitoring but I guess this issue is solved. Thanks a lot for your help! Is there any way to buy you a coffee or something like that? 😀

**Comment by petergridge** [comment] 2024-05-01 04:18
Hi, this is my hobby, just a thanks is fine, next time I am in Germany (?) you can buy me a beer :) It's been two years since I was there! I'll close this issue just reopen or raise a new one if you have more issues.

**Closed** 2024-05-01 04:18 UTC
