### ISSUE TITLE
Water switch never turns off

### ISSUE THREAD

**Issue by asafhas** [petergridge/Irrigation-V5#22] opened 2023-05-17 14:49 UTC
Hello,

After upgrading to version 5.2.0 I've noticed that sometimes the water switch remains ON forever. Happens about 1 out of 10 times.
I've added a few debug prints and saw this:
- Function async_turn_on in irrigationzone.py is called and turns ON the water switch successfully.
- No flow sensor is configured.
- Going into wait-cycle loop: "while watertime > 0: seconds_run += 1"...
- Then the call to "if self.check_switch_state()" returns TRUE (meaning switch is OFF). Even though the switch was just turned ON 1 sec before.
- The program exists with "stop = True", but the switch remains ON forever.
- Even the call to "self.async_turn_off" at the end doesn't turn OFF the water switch.

Maybe there is a race-condition between when the switch is turned ON, and when you test if it's OFF.
There is a 1sec sleep between, maybe it's not enough?

Thank you.

**Comment by petergridge** [comment] 2023-05-18 00:41
Hi @asafhas,

Can you provide me the config you have; How many programs and the settings, each zone's settings.
Just to clarify the issue:
The individual zones are turning on/off as expected but the program is still appearing as running once all zones have completed their cycles?

**Comment by petergridge** [comment] 2023-05-18 01:24
Hi,

Can you also let me know the irrigation switches/device you are using, this may have an impact, I have local control of my switching, but if you have a cloud based solution or one that has high latency this may change how the system behaves.

**Comment by petergridge** [comment] 2023-05-18 01:57
I think if this is a latency issue you can move the 'await asyncio.sleep(1)' to immediately before the 'self.check_switch_state()'. It will help giving an additional second for the status to update without impacting the refresh cycle.

I will update my repository, but if you do make the change let me know if it resolves the issue.

**Comment by petergridge** [comment] 2023-05-18 02:04
I have made the change, V5.2.3 has been published as a Beta. Please let me know if this resolves the issue and I will make it the main release.

**Comment by petergridge** [comment] 2023-05-18 06:05
I managed to create a dummy high latency switch, the behaviour of the program was very odd. I will have a new version, 5.2.4,  that handles the high latency issue on turn on and turn off more elegantly, and provide warning in the log if it is encountered.

I am handling latency of up to 10 seconds that should be ample for almost all situations, touch wood.

```
switch:
  - platform: template
    switches:
      dummy_1:
        friendly_name: Zone 1
        value_template: "{{ is_state('input_boolean.dummy_switch_1', 'on') }}"
        turn_on:
          - delay: '00:00:06'
          - service: input_boolean.turn_on
            entity_id: input_boolean.dummy_switch_1
        turn_off:
          - delay: '00:00:06'
          - service: input_boolean.turn_off
            entity_id: input_boolean.dummy_switch_1

input_boolean:
  dummy_switch_1:
```

**Comment by asafhas** [comment] 2023-05-18 13:56
Thank you for the quick reply.
Regarding your questions above:
- I have 2 programs, 1 zone in each. The issue above happened in both programs.
- The relays I use are connected to ESP8285 chip, running Tasmota, on a local network.

I've copied the relevant changes from version 5.2.4 and will let it run for a few days. I'll update here.

When trying the new code, I saw one time the two prints: "Switch has significant delay skipping" and "Switch has excesive latency".
When it happened I've noticed that the program stopped (only had "RUN" button in the UI), but the zone kept running (had "STOP" button in the UI). The water switch itself was ON.
I couldn't reproduce it again, yet.

**Comment by petergridge** [comment] 2023-05-18 23:50
5.2.4  sends a stop to the switch if the latency is to long, but if this works is dependant on your device, I can only use the emulated model above. the program can't wait indefinitely either as this has the potential of hanging the program.

I am not sure what other failsafe I can put in place. You may need to create an automation, that turns off the switch if the program is not running

I would investigate if you are having connectivity issues with your device or maybe your MQTT config as a 10 second delay is excessive. Have you considered using ESPHOME? I believe it will work on the 8285

**Comment by petergridge** [comment] 2023-05-24 01:09
Hi, I have released v5.2.5 that rolls back the root cause of the problem. If the problem is solved for you can you close the issue.

Cheers
Pete

**Comment by asafhas** [comment] 2023-05-24 14:25
I've been running the code with the previous fix for 5 days, and so far so good.
I see that the new fix in version 5.2.5 is different. I'll upgrade to that version and let it run for a few days.

**Closed** 2023-06-01 05:27 UTC

**Comment by asafhas** [comment] 2023-06-01 07:00
I've been running with version 5.2.5 for the passed week, and all is working good.
Thank you for the quick support.

**Comment by maxoss** [comment] 2023-09-12 16:24
I'm not sure if its related to this but if I manually run a zone the delay to on state and countdown is huge around 17sec. I thought it has something to do with my old switch but now I have new one and still have this issue. 
When I run the full program manually, the switch starts instantly.
